# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'Merchant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Merchant
  pod 'Alamofire', '~> 5.0.0-rc'
  pod 'JWTDecode', '~> 2.4'

  target 'MerchantTests' do
    inherit! :search_paths
#    pod 'Alamofire', '~> 5.0'
    # Pods for testing
  end

  target 'MerchantUITests' do
 # pod 'Alamofire', '~> 5.0'
    # Pods for testing
  end

end
